### ISSUE TITLE
No sound with portable install

### ISSUE THREAD

**Issue by DrSpatula** [ev1l0rd-portableapps/TerrariaPortable#2]
Followed your instructions to the letter setting up a portable version of Terraria on my USB stick, but I have no sound at all in-game.

Just tried installing a copy traditionally and it's working fine with sound. 

Any ideas on what could be the cause?  I've checked all my Windows sound settings and tried deleting Terraria's config and neither yielded anything helpful.

**Comment by zoekay** [comment]
Same here. Any fix on this?

**Comment by noirscape** [comment]
I haven't touched this application in several years, don't feel like touching it again and hereby I'm marking it as unsupported.

Locate your own solutions.
